#ifndef CERESOPTIMIZATION_H
#define CERESOPTIMIZATION_H

#include <flec/datastructure.h>
#include <ceres/ceres.h>
#include <Eigen/Dense>



//Class that manages the whole ceres problem implementation, generated by OdometryExtractor
class ceresOptimization {


public:
    ceresOptimization(tfAccumulator& Buffer);
    ~ceresOptimization();

 /*    
  class JIterationCallback : public ceres::IterationCallback {
  public:
    
    ceres::CRSMatrix jacobian;

    JIterationCallback();

    ~JIterationCallback();

      ceres::CallbackReturnType operator ()(ceres::Problem problem, std::vector<double*> parameterBlocks);
  };
*/




//Cost Function definition
    struct CostFunction {

        Eigen::Matrix4d Tl1_cf;
        Eigen::Matrix4d Tl2_cf;

        CostFunction(Eigen::Matrix4d input_t1, Eigen::Matrix4d input_t2);
        

        template <typename T>
        bool operator()(const T* const q, const T* const t, T* residuals) const;


    private:
    Eigen::Quaternion<double> q1_;
    Eigen::Quaternion<double> q2_;
    Eigen::Matrix<double, 3, 1> t1_;
    Eigen::Matrix<double, 3, 1> t2_;


    };

    void setInitial(Eigen::Vector3d t, Eigen::Quaterniond q)
    {
        this->q_ = q;
        this->t_ = t;
    }


    Optimization_Result solve();


private:

    tfAccumulator buffer_;
    ceres::Problem problem_;
    Eigen::Matrix4d Tl1_;
    Eigen::Matrix4d Tl2_;

    Eigen::Quaterniond q_;  // Quaternion parameters
    Eigen::Vector3d t_;  // Translation parameters

    
};



#endif // CERESOPTIMIZATION_H
