#ifndef CERESOPTIMIZATION_H
#define CERESOPTIMIZATION_H

#include <flec/datastructure.h>
#include <ceres/ceres.h>
#include <Eigen/Dense>

//Class that manages the whole ceres problem implementation, generated by OdometryExtractor
class ceresOptimization {
public:
    ceresOptimization(tfAccumulator& Buffer);
    ~ceresOptimization();



//Cost Function definition
    struct CostFunction {

        Eigen::Matrix4d Tl1_cf;
        Eigen::Matrix4d Tl2_cf;

        CostFunction(Eigen::Matrix4d input_t1, Eigen::Matrix4d input_t2);
        

        template <typename T>
        bool operator()(const T* const q, const T* const t, T* residuals) const;
        


    private:
    Eigen::Quaternion<double> q1_;
    Eigen::Quaternion<double> q2_;
    Eigen::Matrix<double, 3, 1> t1_;
    Eigen::Matrix<double, 3, 1> t2_;


    };

    Optimization_Result solve();

    static Eigen::Matrix<double, 3, 3> SO3Exp(const Eigen::Matrix<double, 3, 1>& input_vector_);
 
    template <typename T>
    static Eigen::Matrix<T, 3, 1> SO3Log( Eigen::Matrix<T, 3, 3>& input_matrix_);

    static Eigen::Matrix<double, 3, 3> skewSymmetric(const Eigen::Matrix<double, 3, 1>& input_vector_);

private:

    tfAccumulator buffer_;
    ceres::Problem problem_;
    Eigen::Matrix4d Tl1_;
    Eigen::Matrix4d Tl2_;
    Eigen::Vector4d q_;  // Quaternion parameters
    Eigen::Vector3d t_;  // Translation parameters
    static constexpr double EPSILON = 1.0e-4;
};



#endif // CERESOPTIMIZATION_H
